---

- name: "install Ansible dependencies"
  become: true
  apt:
    name: ["nodejs", "npm", "python3", "tar", "gzip", "git"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "start PM2"
  become_user: ubuntu
  become: yes
  shell: |
    cd ~/app/backend
    pm2 start npm --name backend -- start